export const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';

export const BEGIN_AJAX_REQUEST = 'BEGIN_AJAX_REQUEST';
export const COMPLETE_AJAX_REQUEST = 'COMPLETE_AJAX_REQUEST';
export const AJAX_REQUEST_ERROR = 'AJAX_REQUEST_ERROR';
